apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netwhip.fullname" . }}
  labels:
    app: {{ include "netwhip.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "netwhip.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "netwhip.name" . }}
    spec:
      containers:
        - name: netwhip
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "-c", "sleep infinity"]
          resources: {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
